"""empty message

Revision ID: 534640296718
Revises: adf763d0035b
Create Date: 2020-04-12 15:07:04.228057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '534640296718'
down_revision = 'adf763d0035b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=192), nullable=True))
    op.add_column('user', sa.Column('id', sa.String(length=192), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=192), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.drop_index('ix_user_Created At', table_name='user')
    op.drop_index('ix_user_Updated At', table_name='user')
    op.drop_constraint('user_Email_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'Created At')
    op.drop_column('user', 'Password')
    op.drop_column('user', 'ID')
    op.drop_column('user', 'Email')
    op.drop_column('user', 'Updated At')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Updated At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('Email', sa.VARCHAR(length=192), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ID', sa.VARCHAR(length=192), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('Password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('Created At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_Email_key', 'user', ['Email'])
    op.create_index('ix_user_Updated At', 'user', ['Updated At'], unique=False)
    op.create_index('ix_user_Created At', 'user', ['Created At'], unique=False)
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'password')
    op.drop_column('user', 'id')
    op.drop_column('user', 'email')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
