"""empty message

Revision ID: adf763d0035b
Revises: 
Create Date: 2020-04-12 15:01:23.136703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf763d0035b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', sa.String(length=192), nullable=False),
    sa.Column('Created At', sa.DateTime(), nullable=True),
    sa.Column('Updated At', sa.DateTime(), nullable=True),
    sa.Column('Email', sa.String(length=192), nullable=True),
    sa.Column('Password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Email')
    )
    op.create_index(op.f('ix_user_Created At'), 'user', ['Created At'], unique=False)
    op.create_index(op.f('ix_user_Updated At'), 'user', ['Updated At'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_Updated At'), table_name='user')
    op.drop_index(op.f('ix_user_Created At'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
